### PR TITLE
Create GETTINGSTARTED.md

### PR DESCRIPTION
**Pull request by mrsanz**

### CODE REVIEW

**Comment by rrrutledge** [comment]
If I remember right this doesn't actually work end-to-end yet (right)?  So these instructions are just a start?

**Comment by mrsanz** [comment]
correct. these are a stub that needs to be completed.

**Comment by rrrutledge** [comment]
So what review is requested here?

**Comment by mrsanz** [comment]
I can close this out and someone else can pick up the branch I guess.

**Pull request closed without merging**
